// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/4/2026, 8:59:10
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/plugins/**/*.{js,ts,mjs}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/composables/**/*.{js,ts,mjs}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/utils/**/*.{js,ts,mjs}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/fmasa/Felix/Desarrollo/Frontend/stack-atlas-hub/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;